export const UPDATE_BOOKS_API_RESPONSE_STATUS = "UPDATE_BOOKS_API_RESPONSE_STATUS"
export const HANDLE_SEARCH_TERM = "HANDLE_SEARCH_TERM"; 
export const SAVE_BOOKS_DATA_IN_STATE = "SAVE_BOOKS_DATA_IN_STATE";
export const SORT_BOOKS = "SORT_BOOKS ";